DROP DATABASE StoreDB;
CREATE DATABASE StoreDB;
USE StoreDB;

CREATE TABLE Products (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FamilyId UNIQUEIDENTIFIER NOT NULL,
    Code NVARCHAR(50) NOT NULL ,    -- UNIQUE
    Name NVARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FKProductsFamily FOREIGN KEY (FamilyId)
        REFERENCES ProductFamilies(Id)
);

CREATE TABLE ProductFamilies (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);