DROP DATABASE Store;
CREATE DATABASE Store;
USE Store;

CREATE TABLE Users(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Salt NVARCHAR(1) NOT NULL
)

CREATE TABLE ProductFamilies (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Products (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FamilyId UNIQUEIDENTIFIER NOT NULL,
    Code NVARCHAR(50) NOT NULL ,    -- UNIQUE
    Name NVARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Discount DECIMAL(5, 2) NOT NULL,
    CONSTRAINT FKProductsFamily FOREIGN KEY (FamilyId)
        REFERENCES ProductFamilies(Id)
);

CREATE TABLE ShoppingCarts (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    ShoppingDate DATE NOT NULL,
    CONSTRAINT FKUsers FOREIGN KEY (UserId)
        REFERENCES Users(Id)
);

CREATE TABLE ShoppingCartsProducts (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ShoppingCartId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    Quantity INT NOT NULL, 
    CONSTRAINT FKShoppingCartsProductsShoppingCarts FOREIGN KEY (ShoppingCartId)
        REFERENCES ShoppingCarts(Id),
    CONSTRAINT FKShoppingCartsProductsProducts FOREIGN KEY (ProductId)
        REFERENCES Products(Id)
);