DROP DATABASE StoreDB;
CREATE DATABASE StoreDB;
USE StoreDB;

CREATE TABLE ProductFamilies (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Products (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FamilyId UNIQUEIDENTIFIER NOT NULL,
    Code NVARCHAR(50) NOT NULL ,    -- UNIQUE
    Name NVARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Discount DECIMAL(5, 2) NOT NULL,
    CONSTRAINT FKProductsFamily FOREIGN KEY (FamilyId)
        REFERENCES ProductFamilies(Id)
);

CREATE TABLE ShoppingCarts (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY
);

CREATE TABLE ShoppingCartsProducts (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ShoppingCartId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    Quantity INT NOT NULL, 
    CONSTRAINT FKShoppingCartsProductsShoppingCarts FOREIGN KEY (ShoppingCartId)
        REFERENCES ShoppingCarts(Id),
    CONSTRAINT FKShoppingCartsProductsProducts FOREIGN KEY (ProductId)
        REFERENCES Products(Id)
);